### ISSUE TITLE
Has encountered a critical error when generate TS File

### ISSUE THREAD

**Issue by Derek-Hu** [fjc0k/yapi-to-typescript#6]
ℹ 获取接口 JSON 文件中...                                                                                           17:58:04
ℹ 生成 TypeScript 类型文件中...                                                                                     17:58:05
(node:28815) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'list' of null
    at /Users/myhome/workspaces/myProject/node_modules/yapi-to-typescript/lib/index.js:26:33
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/Users/myhome/workspaces/myProject/node_modules/yapi-to-typescript/lib/index.js:25:57)
    at step (/Users/myhome/workspaces/myProject/node_modules/tslib/tslib.js:133:27)
    at Object.next (/Users/myhome/workspaces/myProject/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/Users/myhome/workspaces/myProject/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

version:
node: v8.11.4
npm: 5.6.0

**Comment by fjc0k** [comment]
使用的是哪种登录方式？

**Comment by Derek-Hu** [comment]
用户名&密码方式

**Comment by Derek-Hu** [comment]
Users/myhome/workspaces/myProject/node_modules/yapi-to-typescript/lib/index.js:25:57
---------
categoryIdToApiList = apiCollection.reduce(function (res, api) {
                        if (api.list.length) {
                            res[api.list[0].catid] = api.list;
                        }
                        return res;
                    }, {});
----------
发现apiCollection数组有数据，但是reduce时，会出现api为null的情况

**Comment by fjc0k** [comment]
@Derek-Hu 了然。试试最新版，就做了如下改动：

```js
    if (api && api.list && api.list.length) {
      res[api.list[0].catid] = api.list
    }
```
