### ISSUE TITLE
可否支持  /project/{projectId}  类型的动态参数

### ISSUE THREAD

**Issue by WangShuXian6** [fjc0k/yapi-to-typescript#73]
## 描述
>当 projectId 表示动态参数时

>目前本工具支持的格式为标准格式 `/project/:projectId`

>部分spring后端接口生成的swaager文档路由地址格式为 `/project/{projectId}`
>自动生成时会报错
```bash
yarn run v1.22.19
$ npx ytt
✔ 找到配置文件: /Users/wangshuxian/work/decision-engine/ytt.config.ts                                                                                          16:38:20
✔ 获取数据并生成代码完毕                                                                                                                                       16:38:27
/Users/wangshuxian/work/decision-engine/node_modules/p-cancelable/index.js:48
                                        throw new Error('The `onCancel` handler was attached after the promise settled.');
                                              ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/wangshuxian/work/decision-engine/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/Users/wangshuxian/work/decision-engine/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/wangshuxian/work/decision-engine/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:640:26)
    at Request.emit (node:events:520:28)
    at Timeout.retry (/Users/wangshuxian/work/decision-engine/node_modules/got/dist/source/core/index.js:1278:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by WangShuXian6** [comment]
原谅我的粗心，原来该功能已经支持，对不起！
